# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

#trigger:
#- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#Clone the uplink-c-repo
- task: CmdLine@2
  inputs:
    script: |
      SET STORJ_VERSION=v1.1.0
      
      echo *** Cloning uplink-c version %STORJ_VERSION%
      git clone --branch %STORJ_VERSION% https://github.com/storj/uplink-c.git
      
      echo *** Copying necessary files
      copy .\SWIG\*.i .\uplink-c\ /Y
      copy .\SWIG\*.exe .\uplink-c\ /Y
      copy .\GO\*.go .\uplink-c\ /Y
      
      cd .\uplink-c\
      
      echo *** Replacing the version-variable within the DLL
      fart "storj_uplink_second.i" "STORJVERSION" "%STORJ_VERSION%"

      echo *** Installing SWIG
      curl.exe --output swig.zip --url https://deac-fra.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '**/*.zip'
          cleanDestinationFolder: false
          overwriteExistingFiles: false
      
      echo *** Running SWIG to generate a c-file to be add to the dll
      swig -csharp -namespace uplink.SWIG storj_uplink_first.i
      
      echo *** Generating Windows-x64-DLL for the first time - this produces a necessary h-file
      set CC=gcc
      set CXX=g++
      set GOARCH=amd64
      set CGO_ENABLED=1
      go build -ldflags="-s -w '-extldflags=-Wl,--dynamicbase,--high-entropy-va'" -o storj_uplink.dll -buildmode c-shared
      
      echo *** Deleting generated cs-files
      del *.cs
      
      echo *** Deleting generated c-files
      del *.c
      
      echo *** Deleting generated dll-files
      del *.dll
      
      echo *** Removing some types that lead to errors with SWIG
      findstr /V "GoComplex" storj_uplink.h > storj_uplink2.h
      echo *** Removing unnecessary static check
      findstr /V "pointer_matching_GoInt" storj_uplink2.h > storj_uplink3.h
      del storj_uplink.h
      del storj_uplink2.h
      ren storj_uplink3.h storj_uplink.h
      
      echo *** Running SWIG again with the second i-file. It includes more typemaps.
      swig -csharp -namespace uplink.SWIG storj_uplink_second.i
      
      echo *** Generating Windows-x86-DLL - this is the final-x86-DLL for Windows
      set CC=i686-w64-mingw32-gcc
      set CXX=i686-w64-mingw32-g++
      set GOARCH=386
      set CGO_ENABLED=1
      set CGO_CFLAGS=-g -O2 -Wl,--kill-at
      set CGO_CXXFLAGS=-g -O2 -Wl,--kill-at
      set CGO_FFLAGS=-g -O2 -Wl,--kill-at
      set CGO_LDFLAGS=-g -O2 -Wl,--kill-at
      go build -ldflags="-s -w '-extldflags=-Wl,--dynamicbase,--high-entropy-va'"  -o storj_uplink-x86.dll -buildmode c-shared
      echo *** Generating Windows-x64-DLL - this is the final-x64-DLL for Windows
      set CC=gcc
      set CXX=g++
      set GOARCH=amd64
      set CGO_ENABLED=1
      set CGO_CFLAGS=-g -O2
      set CGO_CXXFLAGS=-g -O2
      set CGO_FFLAGS=-g -O2
      set CGO_LDFLAGS=-g -O2
      go build -ldflags="-s -w '-extldflags=-Wl,--dynamicbase,--high-entropy-va'" -o storj_uplink.dll -buildmode c-shared
      
      echo *** Replacing ref-modifier from free_string-method
      fart "storj_uplink.cs" "storj_uplinkPINVOKE.free_string(ref tmpp0);" "storj_uplinkPINVOKE.free_string(tmpp0);"
      fart "storj_uplinkPINVOKE.cs" "public static extern void free_string(ref global::System.IntPtr jarg1);" "public static extern void free_string(global::System.IntPtr jarg1);"
    failOnStderr: true
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
