//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class BucketListOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BucketListOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BucketListOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BucketListOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_BucketListOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string cursor {
    set {
      storj_uplinkPINVOKE.BucketListOptions_cursor_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.BucketListOptions_cursor_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte direction {
    set {
      storj_uplinkPINVOKE.BucketListOptions_direction_set(swigCPtr, value);
    } 
    get {
      sbyte ret = storj_uplinkPINVOKE.BucketListOptions_direction_get(swigCPtr);
      return ret;
    } 
  }

  public long limit {
    set {
      storj_uplinkPINVOKE.BucketListOptions_limit_set(swigCPtr, value);
    } 
    get {
      long ret = storj_uplinkPINVOKE.BucketListOptions_limit_get(swigCPtr);
      return ret;
    } 
  }

  public BucketListOptions() : this(storj_uplinkPINVOKE.new_BucketListOptions(), true) {
  }

}

}
