//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public enum CipherSuite {
  STORJ_ENC_UNSPECIFIED = 0,
  STORJ_ENC_NULL = 1,
  STORJ_ENC_AESGCM = 2,
  STORJ_ENC_SECRET_BOX = 3
}

}
