//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class EdgeCredentials : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EdgeCredentials(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EdgeCredentials obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EdgeCredentials() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_EdgeCredentials(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string access_key_id {
    set {
      storj_uplinkPINVOKE.EdgeCredentials_access_key_id_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.EdgeCredentials_access_key_id_get(swigCPtr);
      return ret;
    } 
  }

  public string secret_key {
    set {
      storj_uplinkPINVOKE.EdgeCredentials_secret_key_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.EdgeCredentials_secret_key_get(swigCPtr);
      return ret;
    } 
  }

  public string endpoint {
    set {
      storj_uplinkPINVOKE.EdgeCredentials_endpoint_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.EdgeCredentials_endpoint_get(swigCPtr);
      return ret;
    } 
  }

  public EdgeCredentials() : this(storj_uplinkPINVOKE.new_EdgeCredentials(), true) {
  }

}

}
