//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class EdgeConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EdgeConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EdgeConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EdgeConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_EdgeConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string auth_service_address {
    set {
      storj_uplinkPINVOKE.EdgeConfig_auth_service_address_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.EdgeConfig_auth_service_address_get(swigCPtr);
      return ret;
    } 
  }

  public string certificate_pem {
    set {
      storj_uplinkPINVOKE.EdgeConfig_certificate_pem_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.EdgeConfig_certificate_pem_get(swigCPtr);
      return ret;
    } 
  }

  public EdgeConfig() : this(storj_uplinkPINVOKE.new_EdgeConfig(), true) {
  }

}

}
