//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public enum ListDirection {
  STORJ_BEFORE = -2,
  STORJ_BACKWARD = -1,
  STORJ_FORWARD = 1,
  STORJ_AFTER = 2
}

}
