//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class ObjectMeta : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ObjectMeta(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ObjectMeta obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ObjectMeta() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_ObjectMeta(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string bucket {
    set {
      storj_uplinkPINVOKE.ObjectMeta_bucket_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.ObjectMeta_bucket_get(swigCPtr);
      return ret;
    } 
  }

  public string path {
    set {
      storj_uplinkPINVOKE.ObjectMeta_path_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.ObjectMeta_path_get(swigCPtr);
      return ret;
    } 
  }

  public bool is_prefix {
    set {
      storj_uplinkPINVOKE.ObjectMeta_is_prefix_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.ObjectMeta_is_prefix_get(swigCPtr);
      return ret;
    } 
  }

  public string content_type {
    set {
      storj_uplinkPINVOKE.ObjectMeta_content_type_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.ObjectMeta_content_type_get(swigCPtr);
      return ret;
    } 
  }

  public MapRef meta_data {
    set {
      storj_uplinkPINVOKE.ObjectMeta_meta_data_set(swigCPtr, MapRef.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.ObjectMeta_meta_data_get(swigCPtr);
      MapRef ret = (cPtr == global::System.IntPtr.Zero) ? null : new MapRef(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int64_t created {
    set {
      storj_uplinkPINVOKE.ObjectMeta_created_set(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(storj_uplinkPINVOKE.ObjectMeta_created_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int64_t modified {
    set {
      storj_uplinkPINVOKE.ObjectMeta_modified_set(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(storj_uplinkPINVOKE.ObjectMeta_modified_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int64_t expires {
    set {
      storj_uplinkPINVOKE.ObjectMeta_expires_set(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(storj_uplinkPINVOKE.ObjectMeta_expires_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t size {
    set {
      storj_uplinkPINVOKE.ObjectMeta_size_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(storj_uplinkPINVOKE.ObjectMeta_size_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t checksum_bytes {
    set {
      storj_uplinkPINVOKE.ObjectMeta_checksum_bytes_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.ObjectMeta_checksum_bytes_get(swigCPtr);
      SWIGTYPE_p_uint8_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t checksum_length {
    set {
      storj_uplinkPINVOKE.ObjectMeta_checksum_length_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(storj_uplinkPINVOKE.ObjectMeta_checksum_length_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ObjectMeta() : this(storj_uplinkPINVOKE.new_ObjectMeta(), true) {
  }

}

}
