//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class Object : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Object(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Object obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Object() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_Object(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string key {
    set {
      storj_uplinkPINVOKE.Object_key_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.Object_key_get(swigCPtr);
      return ret;
    } 
  }

  public bool is_prefix {
    set {
      storj_uplinkPINVOKE.Object_is_prefix_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.Object_is_prefix_get(swigCPtr);
      return ret;
    } 
  }

  public SystemMetadata system {
    set {
      storj_uplinkPINVOKE.Object_system_set(swigCPtr, SystemMetadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.Object_system_get(swigCPtr);
      SystemMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new SystemMetadata(cPtr, false);
      return ret;
    } 
  }

  public CustomMetadata custom {
    set {
      storj_uplinkPINVOKE.Object_custom_set(swigCPtr, CustomMetadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.Object_custom_get(swigCPtr);
      CustomMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new CustomMetadata(cPtr, false);
      return ret;
    } 
  }

  public Object() : this(storj_uplinkPINVOKE.new_Object(), true) {
  }

}

}
