//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class RedundancyScheme : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RedundancyScheme(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RedundancyScheme obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RedundancyScheme() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_RedundancyScheme(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RedundancyAlgorithm algorithm {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_algorithm_set(swigCPtr, (int)value);
    } 
    get {
      RedundancyAlgorithm ret = (RedundancyAlgorithm)storj_uplinkPINVOKE.RedundancyScheme_algorithm_get(swigCPtr);
      return ret;
    } 
  }

  public int share_size {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_share_size_set(swigCPtr, value);
    } 
    get {
      int ret = storj_uplinkPINVOKE.RedundancyScheme_share_size_get(swigCPtr);
      return ret;
    } 
  }

  public short required_shares {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_required_shares_set(swigCPtr, value);
    } 
    get {
      short ret = storj_uplinkPINVOKE.RedundancyScheme_required_shares_get(swigCPtr);
      return ret;
    } 
  }

  public short repair_shares {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_repair_shares_set(swigCPtr, value);
    } 
    get {
      short ret = storj_uplinkPINVOKE.RedundancyScheme_repair_shares_get(swigCPtr);
      return ret;
    } 
  }

  public short optimal_shares {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_optimal_shares_set(swigCPtr, value);
    } 
    get {
      short ret = storj_uplinkPINVOKE.RedundancyScheme_optimal_shares_get(swigCPtr);
      return ret;
    } 
  }

  public short total_shares {
    set {
      storj_uplinkPINVOKE.RedundancyScheme_total_shares_set(swigCPtr, value);
    } 
    get {
      short ret = storj_uplinkPINVOKE.RedundancyScheme_total_shares_get(swigCPtr);
      return ret;
    } 
  }

  public RedundancyScheme() : this(storj_uplinkPINVOKE.new_RedundancyScheme(), true) {
  }

}

}
