//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class storj_uplinkPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="SWIGRegisterExceptionCallbacks_storj_uplink")]
    public static extern void SWIGRegisterExceptionCallbacks_storj_uplink(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_storj_uplink")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_storj_uplink(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_storj_uplink(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_storj_uplink(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(storj_uplinkPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(storj_uplinkPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="SWIGRegisterStringCallback_storj_uplink")]
    public static extern void SWIGRegisterStringCallback_storj_uplink(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_storj_uplink(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static storj_uplinkPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp__GoString__p_set")]
  public static extern void _GoString__p_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp__GoString__p_get")]
  public static extern string _GoString__p_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp__GoString__n_set")]
  public static extern void _GoString__n_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp__GoString__n_get")]
  public static extern global::System.IntPtr _GoString__n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new__GoString_")]
  public static extern global::System.IntPtr new__GoString_();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete__GoString_")]
  public static extern void delete__GoString_(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoInterface_t_set")]
  public static extern void GoInterface_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoInterface_t_get")]
  public static extern global::System.IntPtr GoInterface_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoInterface_v_set")]
  public static extern void GoInterface_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoInterface_v_get")]
  public static extern global::System.IntPtr GoInterface_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_GoInterface")]
  public static extern global::System.IntPtr new_GoInterface();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_GoInterface")]
  public static extern void delete_GoInterface(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_data_set")]
  public static extern void GoSlice_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_data_get")]
  public static extern global::System.IntPtr GoSlice_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_len_set")]
  public static extern void GoSlice_len_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_len_get")]
  public static extern long GoSlice_len_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_cap_set")]
  public static extern void GoSlice_cap_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_GoSlice_cap_get")]
  public static extern long GoSlice_cap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_GoSlice")]
  public static extern global::System.IntPtr new_GoSlice();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_GoSlice")]
  public static extern void delete_GoSlice(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_parse_api_key")]
  public static extern global::System.IntPtr parse_api_key(string jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_serialize_api_key")]
  public static extern string serialize_api_key(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_api_key")]
  public static extern void free_api_key(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_string")]
  public static extern void free_string(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_create_bucket")]
  public static extern global::System.IntPtr create_bucket(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_get_bucket_info")]
  public static extern global::System.IntPtr get_bucket_info(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_open_bucket")]
  public static extern global::System.IntPtr open_bucket(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_list_buckets")]
  public static extern global::System.IntPtr list_buckets(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_bucket")]
  public static extern void delete_bucket(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_close_bucket")]
  public static extern void close_bucket(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_bucket_info")]
  public static extern void free_bucket_info(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_bucket_list")]
  public static extern void free_bucket_list(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_map_ref")]
  public static extern global::System.IntPtr new_map_ref();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_map_ref_set")]
  public static extern void map_ref_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_map_ref_get")]
  public static extern string map_ref_get(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_map_ref_del")]
  public static extern void map_ref_del(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_map_ref")]
  public static extern void delete_map_ref(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_open_object")]
  public static extern global::System.IntPtr open_object(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_close_object")]
  public static extern void close_object(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_get_object_meta")]
  public static extern global::System.IntPtr get_object_meta(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_object_meta")]
  public static extern void free_object_meta(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_upload")]
  public static extern global::System.IntPtr upload(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_upload_opts")]
  public static extern void free_upload_opts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_upload_write")]
  public static extern int upload_write(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_upload_close")]
  public static extern void upload_close(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_list_objects")]
  public static extern global::System.IntPtr list_objects(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_object_info")]
  public static extern void free_object_info(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_free_list_objects")]
  public static extern void free_list_objects(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_download")]
  public static extern global::System.IntPtr download(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ref global::System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_download_read")]
  public static extern int download_read(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, ref global::System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_download_close")]
  public static extern void download_close(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_open_project")]
  public static extern global::System.IntPtr open_project(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, ref global::System.IntPtr jarg5);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_close_project")]
  public static extern void close_project(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_internal_UniverseIsEmpty")]
  public static extern byte internal_UniverseIsEmpty();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_uplink")]
  public static extern global::System.IntPtr new_uplink(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_close_uplink")]
  public static extern void close_uplink(global::System.Runtime.InteropServices.HandleRef jarg1, ref global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_APIKeyRef__handle_set")]
  public static extern void APIKeyRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_APIKeyRef__handle_get")]
  public static extern int APIKeyRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_APIKeyRef")]
  public static extern global::System.IntPtr new_APIKeyRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_APIKeyRef")]
  public static extern void delete_APIKeyRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkRef__handle_set")]
  public static extern void UplinkRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkRef__handle_get")]
  public static extern int UplinkRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UplinkRef")]
  public static extern global::System.IntPtr new_UplinkRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UplinkRef")]
  public static extern void delete_UplinkRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ProjectRef__handle_set")]
  public static extern void ProjectRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ProjectRef__handle_get")]
  public static extern int ProjectRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ProjectRef")]
  public static extern global::System.IntPtr new_ProjectRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ProjectRef")]
  public static extern void delete_ProjectRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketRef__handle_set")]
  public static extern void BucketRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketRef__handle_get")]
  public static extern int BucketRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_BucketRef")]
  public static extern global::System.IntPtr new_BucketRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_BucketRef")]
  public static extern void delete_BucketRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_MapRef__handle_set")]
  public static extern void MapRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_MapRef__handle_get")]
  public static extern int MapRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_MapRef")]
  public static extern global::System.IntPtr new_MapRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_MapRef")]
  public static extern void delete_MapRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectRef__handle_set")]
  public static extern void ObjectRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectRef__handle_get")]
  public static extern int ObjectRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ObjectRef")]
  public static extern global::System.IntPtr new_ObjectRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ObjectRef")]
  public static extern void delete_ObjectRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_DownloaderRef__handle_set")]
  public static extern void DownloaderRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_DownloaderRef__handle_get")]
  public static extern int DownloaderRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_DownloaderRef")]
  public static extern global::System.IntPtr new_DownloaderRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_DownloaderRef")]
  public static extern void delete_DownloaderRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploaderRef__handle_set")]
  public static extern void UploaderRef__handle_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploaderRef__handle_get")]
  public static extern int UploaderRef__handle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UploaderRef")]
  public static extern global::System.IntPtr new_UploaderRef();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UploaderRef")]
  public static extern void delete_UploaderRef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkConfig_Volatile_get")]
  public static extern global::System.IntPtr UplinkConfig_Volatile_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UplinkConfig")]
  public static extern global::System.IntPtr new_UplinkConfig();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UplinkConfig")]
  public static extern void delete_UplinkConfig(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkConfig_Volatile_TLS_get")]
  public static extern global::System.IntPtr UplinkConfig_Volatile_TLS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UplinkConfig_Volatile")]
  public static extern global::System.IntPtr new_UplinkConfig_Volatile();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UplinkConfig_Volatile")]
  public static extern void delete_UplinkConfig_Volatile(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_set")]
  public static extern void UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_get")]
  public static extern bool UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UplinkConfig_Volatile_TLS")]
  public static extern global::System.IntPtr new_UplinkConfig_Volatile_TLS();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UplinkConfig_Volatile_TLS")]
  public static extern void delete_UplinkConfig_Volatile_TLS(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ProjectOptions_key_set")]
  public static extern void ProjectOptions_key_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ProjectOptions_key_get")]
  public static extern string ProjectOptions_key_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ProjectOptions")]
  public static extern global::System.IntPtr new_ProjectOptions();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ProjectOptions")]
  public static extern void delete_ProjectOptions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionParameters_cipher_suite_set")]
  public static extern void EncryptionParameters_cipher_suite_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionParameters_cipher_suite_get")]
  public static extern global::System.IntPtr EncryptionParameters_cipher_suite_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionParameters_block_size_set")]
  public static extern void EncryptionParameters_block_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionParameters_block_size_get")]
  public static extern global::System.IntPtr EncryptionParameters_block_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_EncryptionParameters")]
  public static extern global::System.IntPtr new_EncryptionParameters();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_EncryptionParameters")]
  public static extern void delete_EncryptionParameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_algorithm_set")]
  public static extern void RedundancyScheme_algorithm_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_algorithm_get")]
  public static extern global::System.IntPtr RedundancyScheme_algorithm_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_share_size_set")]
  public static extern void RedundancyScheme_share_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_share_size_get")]
  public static extern global::System.IntPtr RedundancyScheme_share_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_required_shares_set")]
  public static extern void RedundancyScheme_required_shares_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_required_shares_get")]
  public static extern global::System.IntPtr RedundancyScheme_required_shares_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_repair_shares_set")]
  public static extern void RedundancyScheme_repair_shares_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_repair_shares_get")]
  public static extern global::System.IntPtr RedundancyScheme_repair_shares_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_optimal_shares_set")]
  public static extern void RedundancyScheme_optimal_shares_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_optimal_shares_get")]
  public static extern global::System.IntPtr RedundancyScheme_optimal_shares_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_total_shares_set")]
  public static extern void RedundancyScheme_total_shares_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_RedundancyScheme_total_shares_get")]
  public static extern global::System.IntPtr RedundancyScheme_total_shares_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_RedundancyScheme")]
  public static extern global::System.IntPtr new_RedundancyScheme();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_RedundancyScheme")]
  public static extern void delete_RedundancyScheme(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_name_set")]
  public static extern void BucketInfo_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_name_get")]
  public static extern string BucketInfo_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_created_set")]
  public static extern void BucketInfo_created_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_created_get")]
  public static extern global::System.IntPtr BucketInfo_created_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_path_cipher_set")]
  public static extern void BucketInfo_path_cipher_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_path_cipher_get")]
  public static extern global::System.IntPtr BucketInfo_path_cipher_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_segment_size_set")]
  public static extern void BucketInfo_segment_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_segment_size_get")]
  public static extern global::System.IntPtr BucketInfo_segment_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_encryption_parameters_set")]
  public static extern void BucketInfo_encryption_parameters_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_encryption_parameters_get")]
  public static extern global::System.IntPtr BucketInfo_encryption_parameters_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_redundancy_scheme_set")]
  public static extern void BucketInfo_redundancy_scheme_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketInfo_redundancy_scheme_get")]
  public static extern global::System.IntPtr BucketInfo_redundancy_scheme_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_BucketInfo")]
  public static extern global::System.IntPtr new_BucketInfo();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_BucketInfo")]
  public static extern void delete_BucketInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_path_cipher_set")]
  public static extern void BucketConfig_path_cipher_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_path_cipher_get")]
  public static extern global::System.IntPtr BucketConfig_path_cipher_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_encryption_parameters_set")]
  public static extern void BucketConfig_encryption_parameters_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_encryption_parameters_get")]
  public static extern global::System.IntPtr BucketConfig_encryption_parameters_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_redundancy_scheme_set")]
  public static extern void BucketConfig_redundancy_scheme_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketConfig_redundancy_scheme_get")]
  public static extern global::System.IntPtr BucketConfig_redundancy_scheme_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_BucketConfig")]
  public static extern global::System.IntPtr new_BucketConfig();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_BucketConfig")]
  public static extern void delete_BucketConfig(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_cursor_set")]
  public static extern void BucketListOptions_cursor_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_cursor_get")]
  public static extern string BucketListOptions_cursor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_direction_set")]
  public static extern void BucketListOptions_direction_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_direction_get")]
  public static extern global::System.IntPtr BucketListOptions_direction_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_limit_set")]
  public static extern void BucketListOptions_limit_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketListOptions_limit_get")]
  public static extern global::System.IntPtr BucketListOptions_limit_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_BucketListOptions")]
  public static extern global::System.IntPtr new_BucketListOptions();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_BucketListOptions")]
  public static extern void delete_BucketListOptions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_more_set")]
  public static extern void BucketList_more_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_more_get")]
  public static extern bool BucketList_more_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_items_set")]
  public static extern void BucketList_items_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_items_get")]
  public static extern global::System.IntPtr BucketList_items_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_length_set")]
  public static extern void BucketList_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_BucketList_length_get")]
  public static extern global::System.IntPtr BucketList_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_BucketList")]
  public static extern global::System.IntPtr new_BucketList();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_BucketList")]
  public static extern void delete_BucketList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionAccess_key_set")]
  public static extern void EncryptionAccess_key_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_EncryptionAccess_key_get")]
  public static extern string EncryptionAccess_key_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_EncryptionAccess")]
  public static extern global::System.IntPtr new_EncryptionAccess();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_EncryptionAccess")]
  public static extern void delete_EncryptionAccess(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_version_set")]
  public static extern void ObjectInfo_version_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_version_get")]
  public static extern global::System.IntPtr ObjectInfo_version_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_bucket_set")]
  public static extern void ObjectInfo_bucket_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_bucket_get")]
  public static extern global::System.IntPtr ObjectInfo_bucket_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_path_set")]
  public static extern void ObjectInfo_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_path_get")]
  public static extern string ObjectInfo_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_is_prefix_set")]
  public static extern void ObjectInfo_is_prefix_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_is_prefix_get")]
  public static extern bool ObjectInfo_is_prefix_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_metadata_set")]
  public static extern void ObjectInfo_metadata_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_metadata_get")]
  public static extern global::System.IntPtr ObjectInfo_metadata_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_content_type_set")]
  public static extern void ObjectInfo_content_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_content_type_get")]
  public static extern string ObjectInfo_content_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_created_set")]
  public static extern void ObjectInfo_created_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_created_get")]
  public static extern global::System.IntPtr ObjectInfo_created_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_modified_set")]
  public static extern void ObjectInfo_modified_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_modified_get")]
  public static extern global::System.IntPtr ObjectInfo_modified_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_expires_set")]
  public static extern void ObjectInfo_expires_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectInfo_expires_get")]
  public static extern global::System.IntPtr ObjectInfo_expires_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ObjectInfo")]
  public static extern global::System.IntPtr new_ObjectInfo();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ObjectInfo")]
  public static extern void delete_ObjectInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_bucket_set")]
  public static extern void ObjectList_bucket_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_bucket_get")]
  public static extern string ObjectList_bucket_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_prefix_set")]
  public static extern void ObjectList_prefix_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_prefix_get")]
  public static extern string ObjectList_prefix_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_more_set")]
  public static extern void ObjectList_more_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_more_get")]
  public static extern bool ObjectList_more_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_items_set")]
  public static extern void ObjectList_items_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_items_get")]
  public static extern global::System.IntPtr ObjectList_items_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_length_set")]
  public static extern void ObjectList_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectList_length_get")]
  public static extern global::System.IntPtr ObjectList_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ObjectList")]
  public static extern global::System.IntPtr new_ObjectList();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ObjectList")]
  public static extern void delete_ObjectList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_content_type_set")]
  public static extern void UploadOptions_content_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_content_type_get")]
  public static extern string UploadOptions_content_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_metadata_set")]
  public static extern void UploadOptions_metadata_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_metadata_get")]
  public static extern global::System.IntPtr UploadOptions_metadata_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_expires_set")]
  public static extern void UploadOptions_expires_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_UploadOptions_expires_get")]
  public static extern global::System.IntPtr UploadOptions_expires_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_UploadOptions")]
  public static extern global::System.IntPtr new_UploadOptions();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_UploadOptions")]
  public static extern void delete_UploadOptions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_prefix_set")]
  public static extern void ListOptions_prefix_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_prefix_get")]
  public static extern string ListOptions_prefix_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_cursor_set")]
  public static extern void ListOptions_cursor_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_cursor_get")]
  public static extern string ListOptions_cursor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_delimiter_set")]
  public static extern void ListOptions_delimiter_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_delimiter_get")]
  public static extern char ListOptions_delimiter_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_recursive_set")]
  public static extern void ListOptions_recursive_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_recursive_get")]
  public static extern bool ListOptions_recursive_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_direction_set")]
  public static extern void ListOptions_direction_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_direction_get")]
  public static extern global::System.IntPtr ListOptions_direction_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_limit_set")]
  public static extern void ListOptions_limit_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ListOptions_limit_get")]
  public static extern global::System.IntPtr ListOptions_limit_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ListOptions")]
  public static extern global::System.IntPtr new_ListOptions();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ListOptions")]
  public static extern void delete_ListOptions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_bucket_set")]
  public static extern void ObjectMeta_bucket_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_bucket_get")]
  public static extern string ObjectMeta_bucket_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_path_set")]
  public static extern void ObjectMeta_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_path_get")]
  public static extern string ObjectMeta_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_is_prefix_set")]
  public static extern void ObjectMeta_is_prefix_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_is_prefix_get")]
  public static extern bool ObjectMeta_is_prefix_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_content_type_set")]
  public static extern void ObjectMeta_content_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_content_type_get")]
  public static extern string ObjectMeta_content_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_meta_data_set")]
  public static extern void ObjectMeta_meta_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_meta_data_get")]
  public static extern global::System.IntPtr ObjectMeta_meta_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_created_set")]
  public static extern void ObjectMeta_created_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_created_get")]
  public static extern global::System.IntPtr ObjectMeta_created_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_modified_set")]
  public static extern void ObjectMeta_modified_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_modified_get")]
  public static extern global::System.IntPtr ObjectMeta_modified_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_expires_set")]
  public static extern void ObjectMeta_expires_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_expires_get")]
  public static extern global::System.IntPtr ObjectMeta_expires_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_size_set")]
  public static extern void ObjectMeta_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_size_get")]
  public static extern global::System.IntPtr ObjectMeta_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_checksum_bytes_set")]
  public static extern void ObjectMeta_checksum_bytes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_checksum_bytes_get")]
  public static extern global::System.IntPtr ObjectMeta_checksum_bytes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_checksum_length_set")]
  public static extern void ObjectMeta_checksum_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_ObjectMeta_checksum_length_get")]
  public static extern global::System.IntPtr ObjectMeta_checksum_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_new_ObjectMeta")]
  public static extern global::System.IntPtr new_ObjectMeta();

  [global::System.Runtime.InteropServices.DllImport("storj_uplink", EntryPoint="CSharp_delete_ObjectMeta")]
  public static extern void delete_ObjectMeta(global::System.Runtime.InteropServices.HandleRef jarg1);
}
