//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class UplinkConfig_Volatile_TLS : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkConfig_Volatile_TLS(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkConfig_Volatile_TLS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkConfig_Volatile_TLS() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkConfig_Volatile_TLS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool SkipPeerCAWhitelist {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_TLS_SkipPeerCAWhitelist_get(swigCPtr);
      return ret;
    } 
  }

  public UplinkConfig_Volatile_TLS() : this(storj_uplinkPINVOKE.new_UplinkConfig_Volatile_TLS(), true) {
  }

}

}
