//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class UplinkConfig_Volatile : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkConfig_Volatile(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkConfig_Volatile obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkConfig_Volatile() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkConfig_Volatile(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UplinkConfig_Volatile_TLS TLS {
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UplinkConfig_Volatile_TLS_get(swigCPtr);
      UplinkConfig_Volatile_TLS ret = (cPtr == global::System.IntPtr.Zero) ? null : new UplinkConfig_Volatile_TLS(cPtr, false);
      return ret;
    } 
  }

  public UplinkConfig_Volatile() : this(storj_uplinkPINVOKE.new_UplinkConfig_Volatile(), true) {
  }

}
