//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class UplinkPermission : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkPermission(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkPermission obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkPermission() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkPermission(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool allow_download {
    set {
      storj_uplinkPINVOKE.UplinkPermission_allow_download_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkPermission_allow_download_get(swigCPtr);
      return ret;
    } 
  }

  public bool allow_upload {
    set {
      storj_uplinkPINVOKE.UplinkPermission_allow_upload_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkPermission_allow_upload_get(swigCPtr);
      return ret;
    } 
  }

  public bool allow_list {
    set {
      storj_uplinkPINVOKE.UplinkPermission_allow_list_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkPermission_allow_list_get(swigCPtr);
      return ret;
    } 
  }

  public bool allow_delete {
    set {
      storj_uplinkPINVOKE.UplinkPermission_allow_delete_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkPermission_allow_delete_get(swigCPtr);
      return ret;
    } 
  }

  public long not_before {
    set {
      storj_uplinkPINVOKE.UplinkPermission_not_before_set(swigCPtr, value);
    } 
    get {
      long ret = storj_uplinkPINVOKE.UplinkPermission_not_before_get(swigCPtr);
      return ret;
    } 
  }

  public long not_after {
    set {
      storj_uplinkPINVOKE.UplinkPermission_not_after_set(swigCPtr, value);
    } 
    get {
      long ret = storj_uplinkPINVOKE.UplinkPermission_not_after_get(swigCPtr);
      return ret;
    } 
  }

  public UplinkPermission() : this(storj_uplinkPINVOKE.new_UplinkPermission(), true) {
  }

}

}
