//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class UplinkObject : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkObject(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkObject() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string key {
    set {
      storj_uplinkPINVOKE.UplinkObject_key_set(swigCPtr, new storj_uplinkPINVOKE.SWIGStringMarshal(value).swigCPtr);
    } 
    get {
      string ret = storj_uplinkPINVOKE.SWIGStringMarshal.StringFromNativeUtf8(storj_uplinkPINVOKE.UplinkObject_key_get(swigCPtr));
      return ret;
    } 
  }

  public bool is_prefix {
    set {
      storj_uplinkPINVOKE.UplinkObject_is_prefix_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.UplinkObject_is_prefix_get(swigCPtr);
      return ret;
    } 
  }

  public UplinkSystemMetadata system {
    set {
      storj_uplinkPINVOKE.UplinkObject_system_set(swigCPtr, UplinkSystemMetadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UplinkObject_system_get(swigCPtr);
      UplinkSystemMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new UplinkSystemMetadata(cPtr, false);
      return ret;
    } 
  }

  public UplinkCustomMetadata custom {
    set {
      storj_uplinkPINVOKE.UplinkObject_custom_set(swigCPtr, UplinkCustomMetadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UplinkObject_custom_get(swigCPtr);
      UplinkCustomMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new UplinkCustomMetadata(cPtr, false);
      return ret;
    } 
  }

  public UplinkObject() : this(storj_uplinkPINVOKE.new_UplinkObject(), true) {
  }

}

}
