//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class UplinkCustomMetadata : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkCustomMetadata(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkCustomMetadata obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkCustomMetadata() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkCustomMetadata(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UplinkCustomMetadataEntry entries {
    set {
      storj_uplinkPINVOKE.UplinkCustomMetadata_entries_set(swigCPtr, UplinkCustomMetadataEntry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UplinkCustomMetadata_entries_get(swigCPtr);
      UplinkCustomMetadataEntry ret = (cPtr == global::System.IntPtr.Zero) ? null : new UplinkCustomMetadataEntry(cPtr, false);
      return ret;
    } 
  }

  public uint count {
    set {
      storj_uplinkPINVOKE.UplinkCustomMetadata_count_set(swigCPtr, value);
    } 
    get {
      uint ret = storj_uplinkPINVOKE.UplinkCustomMetadata_count_get(swigCPtr);
      return ret;
    } 
  }

  public UplinkCustomMetadata() : this(storj_uplinkPINVOKE.new_UplinkCustomMetadata(), true) {
  }

}

}
