//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class UploadOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UploadOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UploadOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UploadOptions() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UploadOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string content_type {
    set {
      storj_uplinkPINVOKE.UploadOptions_content_type_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.UploadOptions_content_type_get(swigCPtr);
      return ret;
    } 
  }

  public MapRef metadata {
    set {
      storj_uplinkPINVOKE.UploadOptions_metadata_set(swigCPtr, MapRef.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UploadOptions_metadata_get(swigCPtr);
      MapRef ret = (cPtr == global::System.IntPtr.Zero) ? null : new MapRef(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int64_t expires {
    set {
      storj_uplinkPINVOKE.UploadOptions_expires_set(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(storj_uplinkPINVOKE.UploadOptions_expires_get(swigCPtr), true);
      if (storj_uplinkPINVOKE.SWIGPendingException.Pending) throw storj_uplinkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UploadOptions() : this(storj_uplinkPINVOKE.new_UploadOptions(), true) {
  }

}

}
