//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class BucketList : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BucketList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BucketList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BucketList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_BucketList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool more {
    set {
      storj_uplinkPINVOKE.BucketList_more_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.BucketList_more_get(swigCPtr);
      return ret;
    } 
  }

  public BucketInfo items {
    set {
      storj_uplinkPINVOKE.BucketList_items_set(swigCPtr, BucketInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.BucketList_items_get(swigCPtr);
      BucketInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new BucketInfo(cPtr, false);
      return ret;
    } 
  }

  public int length {
    set {
      storj_uplinkPINVOKE.BucketList_length_set(swigCPtr, value);
    } 
    get {
      int ret = storj_uplinkPINVOKE.BucketList_length_get(swigCPtr);
      return ret;
    } 
  }

  public BucketList() : this(storj_uplinkPINVOKE.new_BucketList(), true) {
  }

}

}
