//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public class Caveat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Caveat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Caveat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Caveat() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_Caveat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool disallow_reads {
    set {
      storj_uplinkPINVOKE.Caveat_disallow_reads_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.Caveat_disallow_reads_get(swigCPtr);
      return ret;
    } 
  }

  public bool disallow_writes {
    set {
      storj_uplinkPINVOKE.Caveat_disallow_writes_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.Caveat_disallow_writes_get(swigCPtr);
      return ret;
    } 
  }

  public bool disallow_lists {
    set {
      storj_uplinkPINVOKE.Caveat_disallow_lists_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.Caveat_disallow_lists_get(swigCPtr);
      return ret;
    } 
  }

  public bool disallow_deletes {
    set {
      storj_uplinkPINVOKE.Caveat_disallow_deletes_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.Caveat_disallow_deletes_get(swigCPtr);
      return ret;
    } 
  }

  public Caveat() : this(storj_uplinkPINVOKE.new_Caveat(), true) {
  }

}

}
