//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class ListObjectsOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ListObjectsOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ListObjectsOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ListObjectsOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_ListObjectsOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string prefix {
    set {
      storj_uplinkPINVOKE.ListObjectsOptions_prefix_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.ListObjectsOptions_prefix_get(swigCPtr);
      return ret;
    } 
  }

  public string cursor {
    set {
      storj_uplinkPINVOKE.ListObjectsOptions_cursor_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.ListObjectsOptions_cursor_get(swigCPtr);
      return ret;
    } 
  }

  public bool recursive {
    set {
      storj_uplinkPINVOKE.ListObjectsOptions_recursive_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.ListObjectsOptions_recursive_get(swigCPtr);
      return ret;
    } 
  }

  public bool system {
    set {
      storj_uplinkPINVOKE.ListObjectsOptions_system_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.ListObjectsOptions_system_get(swigCPtr);
      return ret;
    } 
  }

  public bool custom {
    set {
      storj_uplinkPINVOKE.ListObjectsOptions_custom_set(swigCPtr, value);
    } 
    get {
      bool ret = storj_uplinkPINVOKE.ListObjectsOptions_custom_get(swigCPtr);
      return ret;
    } 
  }

  public ListObjectsOptions() : this(storj_uplinkPINVOKE.new_ListObjectsOptions(), true) {
  }

}

}
