//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

public enum RedundancyAlgorithm {
  STORJ_INVALID_REDUNDANCY_ALGORITHM = 0,
  STORJ_REED_SOLOMON = 1
}

}
