//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace uplink.SWIG {

internal class UplinkConfig_Volatile : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UplinkConfig_Volatile(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UplinkConfig_Volatile obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UplinkConfig_Volatile() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          storj_uplinkPINVOKE.delete_UplinkConfig_Volatile(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UplinkConfig_Volatile_tls tls {
    get {
      global::System.IntPtr cPtr = storj_uplinkPINVOKE.UplinkConfig_Volatile_tls_get(swigCPtr);
      UplinkConfig_Volatile_tls ret = (cPtr == global::System.IntPtr.Zero) ? null : new UplinkConfig_Volatile_tls(cPtr, false);
      return ret;
    } 
  }

  public string peer_id_version {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_peer_id_version_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_peer_id_version_get(swigCPtr);
      return ret;
    } 
  }

  public int max_inline_size {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_max_inline_size_set(swigCPtr, value);
    } 
    get {
      int ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_max_inline_size_get(swigCPtr);
      return ret;
    } 
  }

  public int max_memory {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_max_memory_set(swigCPtr, value);
    } 
    get {
      int ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_max_memory_get(swigCPtr);
      return ret;
    } 
  }

  public int dial_timeout {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_dial_timeout_set(swigCPtr, value);
    } 
    get {
      int ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_dial_timeout_get(swigCPtr);
      return ret;
    } 
  }

  public string user_agent {
    set {
      storj_uplinkPINVOKE.UplinkConfig_Volatile_user_agent_set(swigCPtr, value);
    } 
    get {
      string ret = storj_uplinkPINVOKE.UplinkConfig_Volatile_user_agent_get(swigCPtr);
      return ret;
    } 
  }

  public UplinkConfig_Volatile() : this(storj_uplinkPINVOKE.new_UplinkConfig_Volatile(), true) {
  }

}

}
